# ------------------------------ #
# KITTY THEME                    #
# ------------------------------ #
include current-theme.conf

background_opacity 0.8

# Cursor
cursor_blink_interval = 0.5
cursor_trail 1
cursor_trail_decay 0.1 0.4


# ------------------------------ #
# KITTY FONTS                    #
# ------------------------------ #
font_family      family="JetBrains Mono NL"
bold_font        auto
italic_font      auto
bold_italic_font auto
