$terminal = kitty
$browser = firefox
$editor = vscode
$fileExplorer = dolphin
$musicPlayer = spotify-launcher
$screenshotTool = ~/.config/hypr/scripts/screenshot.sh
$appLauncher = pkill fuzzel || fuzzel 
