exec = hyprctl dispatch submap global
submap = global

source = ~/.config/hypr/apps.conf

# ============================== # 
# Apps                           #
# ============================== # 
bind = Alt, F1, exec, $terminal
bind = Alt, F2, exec, $browser
bind = Alt, F3, exec, $fileExplorer
bind = Alt, F4, exec, $musicPlayer


# ============================== # 
# Media                          #
# ============================== # 
#bindl = Super+Alt, space, DISPATCHER, //MEDIA_PAUSE
#bindl = Super+Alt, left, //DISPATCHER, //MEDIA_NEXT
#bindl = Super+Alt, right, //DISPATCHER, //MEDIA_PREV


# ============================== # 
# Utilities                      #
# ============================== # 
bindl = , print, exec, $screenshotTool
bindr = Super, SUPER_L, exec, $appLauncher
bindl = Ctrl+Alt+Shift, delete, exec, shutdown
bind = Alt, F12, exec, waypaper --config-file ~/.config/waypaper/config.ini


# ============================== # 
# Volume                         #
# ============================== # 
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ $volumeStep%+ # Raise
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ $volumeStep%- # Lower


# ============================== # 
# Workspaces                     # 
# ============================== #

# Swap Workspace
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9

# Go to Workspace -1/+1
bind = Super, mouse_up, workspace, -1
bind = Super, mouse_down, workspace, +1
bind = Super, tab, workspace, +1
bind = Super+Shift, tab, workspace, -1

# Move Window to Workspace
bind = Super+Shift, 1, movetoworkspace, 1
bind = Super+Shift, 2, movetoworkspace, 2
bind = Super+Shift, 3, movetoworkspace, 3
bind = Super+Shift, 4, movetoworkspace, 4
bind = Super+Shift, 5, movetoworkspace, 5
bind = Super+Shift, 6, movetoworkspace, 6
bind = Super+Shift, 7, movetoworkspace, 7
bind = Super+Shift, 8, movetoworkspace, 8
bind = Super+Shift, 9, movetoworkspace, 9

# Switching Windows
bind = Super, left, movefocus, l
bind = Super, right, movefocus, r
bind = Super, up, movefocus, u
bind = Super, down, movefocus, d

# Resizing Windows
binde = Super, minus, resizeactive, -10% 0          # left
binde = Super, equal, resizeactive, 10% 0          # right
binde = Super+Shift, minus, resizeactive, 0 -10%    # up
binde = Super+Shift, equal, resizeactive, 0 10%    # down

# Window Utilities
bind = Super, W, killactive,     # kill window
bindm = Super, Z, movewindow      # move window
bindm = Super, X, resizeactive    # resize window


